### ISSUE TITLE
During bootstrap a race condition can expose ContextualVersionConflict

### ISSUE THREAD

**Issue by whereisrysmind** [openstack-charmers/charm-test-infra#29]
There exists a bug in the requirements such that ContextualVersionConflict can occur while attempting to satisfy package dependencies for 'requests'. Normal use by experienced users or CI procedures will not show it, but If a user attempts to bootstrap the this project without having configured their ssh-agent then this will occur as a result of the delay in entering the ssh key password.

Perhaps the version of 'requests' needs to be bumped somewhere.

Full Error Output:
`clients create: /home/ubuntu/charm-test-infra/.tox/clients
clients installdeps: -r/home/ubuntu/charm-test-infra/py3-clients-requirements.txt
ERROR: invocation failed (exit code 1), logfile: /home/ubuntu/charm-test-infra/.tox/clients/log/clients-1.log
ERROR: actionid: clients
msg: getenv
cmdargs: ['/home/ubuntu/charm-test-infra/.tox/clients/bin/pip', 'install', '-r/home/ubuntu/charm-test-infra/py3-clients-requirements.txt']
env: {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'SSH_CONNECTION': '10.172.67.136 41536 10.5.0.9 22', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LANG': 'C.UTF-8', 'OLDPWD': '/home/ubuntu', 'XDG_SESSION_ID': '29', 'USER': 'ubuntu', 'PWD': '/home/ubuntu/charm-test-infra', 'HOME': '/home/ubuntu', 'SSH_CLIENT': '10.172.67.136 41536 22', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'SSH_TTY': '/dev/pts/0', 'MAIL': '/var/mail/ubuntu', 'TERM': 'screen', 'SHELL': '/bin/bash', 'SHLVL': '1', 'LOGNAME': 'ubuntu', 'XDG_RUNTIME_DIR': '/run/user/1000', 'PATH': '/home/ubuntu/charm-test-infra/.tox/clients/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'PS1': '${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ', 'LESSOPEN': '| /usr/bin/lesspipe %s', '_': '/usr/bin/tox', 'VIRTUAL_ENV': '/home/ubuntu/charm-test-infra/.tox/clients', 'PYTHONHASHSEED': '0'}

Collecting zaza from git+https://github.com/openstack-charmers/zaza.git#egg=zaza (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Cloning https://github.com/openstack-charmers/zaza.git to /tmp/pip-install-dfxhpppw/zaza
  Running command git clone -q https://github.com/openstack-charmers/zaza.git /tmp/pip-install-dfxhpppw/zaza
Collecting juju-crashdump from git+https://github.com/juju/juju-crashdump.git#egg=juju-crashdump (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 5))
  Cloning https://github.com/juju/juju-crashdump.git to /tmp/pip-install-dfxhpppw/juju-crashdump
  Running command git clone -q https://github.com/juju/juju-crashdump.git /tmp/pip-install-dfxhpppw/juju-crashdump
  WARNING: Generating metadata for package juju-crashdump produced metadata for project name jujucrashdump. Fix your #egg=juju-crashdump fragments.
Collecting juju-deployer (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/53/cd/df61d73e42a76b62203902dc2707e4b3f1d7d9ccae72b1babeb7e5765244/juju-deployer-0.11.0.tar.gz
Collecting websocket-client!=0.44.0 (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl
Collecting argcomplete>=0.8.1 (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/2e/22/374114e3e3692002f6aad1038faa3ca062668942da9c43f25c04100cdfb1/argcomplete-1.9.5-py2.py3-none-any.whl
Collecting jinja2>=2.8 (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting setuptools==36.4.0 (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/1b/95/e6f28144fdb6c06186c1f0e70cea02791e6ec787682bdfc437ce69b8186c/setuptools-36.4.0-py2.py3-none-any.whl
Collecting codetree from bzr+lp:codetree#egg=codetree (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 13))
  Checking out lp:codetree to /tmp/pip-install-dfxhpppw/codetree
  Running command bzr branch -q lp:codetree /tmp/pip-install-dfxhpppw/codetree
  WARNING: Generating metadata for package codetree produced metadata for project name python-codetree. Fix your #egg=codetree fragments.
Collecting mojo from bzr+lp:~ost-maintainers/mojo/py3#egg=mojo (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 15))
  Checking out lp:~ost-maintainers/mojo/py3 to /tmp/pip-install-dfxhpppw/mojo
  Running command bzr branch -q 'lp:~ost-maintainers/mojo/py3' /tmp/pip-install-dfxhpppw/mojo
Collecting cmd2!=0.8.3 (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/9d/7c/fc946c24dfe4b12ffdcd099216471c413bbcf48f94f86b91b4ea44ccbaa6/cmd2-0.9.12-py3-none-any.whl
Collecting distro-info (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/91/e0/ccd731d32238bc18bb8ac80353b4028394f80d5ff7db0f93a5ba488690d3/distro-info-0.10.tar.gz
Collecting dnspython (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl
Collecting babel!=2.4.0,>=2.3.4 (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
Collecting paramiko (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl
Collecting python-openstackclient>=3.14.0 (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 23))
  Using cached https://files.pythonhosted.org/packages/94/0b/ce17ff61441fb091ffbfc7bb9c17cffe175c113aa3717c493cc4687901ff/python_openstackclient-3.18.0-py2.py3-none-any.whl
Collecting aodhclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 24))
  Using cached https://files.pythonhosted.org/packages/9b/c6/40058f4bec9fa67f01c6628925dab58f88ee1eebd5a8b41d303715a0d738/aodhclient-1.2.0-py2.py3-none-any.whl
Collecting python-designateclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/ef/f8/95423f61960532a1dfc23db69b2bd4e6d00896089695aec55962a54fb81d/python_designateclient-2.11.0-py2.py3-none-any.whl
Collecting python-barbicanclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 26))
  Using cached https://files.pythonhosted.org/packages/96/9c/9410b618ba4783fa17e138ebbc584d6d95a1f3d42464bfdaa39ad98610d3/python_barbicanclient-4.8.1-py2.py3-none-any.whl
Collecting python-ceilometerclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 27))
  Using cached https://files.pythonhosted.org/packages/62/99/7279d232f5feb96d278d02ba2ac74b04899849681c3463405210b1cd04d1/python_ceilometerclient-2.9.0-py2.py3-none-any.whl
Collecting python-cinderclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 28))
  Using cached https://files.pythonhosted.org/packages/45/c8/4ecc0310dbed47d27c366e6915d9c41a91ce97b8fcdba548de94fc9df655/python_cinderclient-4.1.0-py2.py3-none-any.whl
Collecting python-glanceclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/95/9f/d89598e6145cd381e24082214fc8a0699bce318f1c8d22001a120c5d92ef/python_glanceclient-2.16.0-py2.py3-none-any.whl
Collecting python-heatclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/b7/e3/dcce9798a5212759f1e1e1b1119dfa032708580226e728eb0fe06cb63b8c/python_heatclient-1.17.0-py2.py3-none-any.whl
Collecting python-keystoneclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 31))
  Using cached https://files.pythonhosted.org/packages/a1/89/8a05ef1d3b54cbb01268b767b8fc28d3b58c4c831606f5830e76bf50f388/python_keystoneclient-3.19.0-py2.py3-none-any.whl
Collecting python-neutronclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 32))
  Using cached https://files.pythonhosted.org/packages/b0/f2/2844e46948e400fed14f83da8f2bc45543e172bcb8c8d4863da6aafefc04/python_neutronclient-6.12.0-py2.py3-none-any.whl
Collecting python-novaclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/41/a6/5f820c02c5d148d4d185555522442d2d317b280898efd98af80ab5085bb1/python_novaclient-13.0.0-py2.py3-none-any.whl
Collecting python-swiftclient (from -r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 34))
  Using cached https://files.pythonhosted.org/packages/ae/cd/d1512df8d7cd317bf09b8b0e6cefd578475315e83f9fc71e3c23f528ef5f/python_swiftclient-3.7.0-py2.py3-none-any.whl
Collecting async_generator (from zaza->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/71/52/39d20e03abd0ac9159c162ec24b93fbcaa111e8400308f2465432495ca2b/async_generator-1.10-py3-none-any.whl
Collecting cryptography (from zaza->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/5b/12/b0409a94dad366d98a8eee2a77678c7a73aafd8c0e4b835abea634ea3896/cryptography-2.6.1-cp34-abi3-manylinux1_x86_64.whl
Collecting hvac<0.7.0 (from zaza->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/cc/28/25c2daaa6f89ff3a20b8c88490e2e3dff1f141739cbabb17682d11a828f2/hvac-0.6.4-py2.py3-none-any.whl
Collecting juju (from zaza->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/cd/fd/14ffad016ae20288d9a9ec7ba282ce979c96d2423bd5294cb1e5be1e75c5/juju-0.11.5.tar.gz
Collecting juju-wait (from zaza->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/8b/eb/871cdba5247642b94274c30deeead3c2ee5c833ad51ad1a8a33480f2f287/juju_wait-2.7.0-py2.py3-none-any.whl
Collecting PyYAML (from zaza->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz
Collecting tenacity (from zaza->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/6a/93/dfcf5b1b46ab29196274b78dcba69fab5e54b6dc303a7eed90a79194d277/tenacity-5.0.4-py2.py3-none-any.whl
Collecting oslo.config (from zaza->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ac/28/c367554ceb317156ac9e4ff390e91a9290af9d67cdc17c2ec1ed5e93089b/oslo.config-6.8.1-py2.py3-none-any.whl
Collecting python-octaviaclient (from zaza->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/86/8e/607ec852af5a254816cf03490bac0a3da710ec53b3c6b65e29de755014d7/python_octaviaclient-1.8.0-py2.py3-none-any.whl
Collecting jujuclient>=0.53 (from juju-deployer->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/a1/60/d04bc8c3463fe73a9074ba2978cf1e53ba98b3c388fe3351c5ee1387ca1a/jujuclient-0.54.0.tar.gz
Collecting six (from juju-deployer->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2>=2.8->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting futures (from python-codetree->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz
Collecting requests (from python-codetree->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting pylxd<2.1.0 (from mojo->-r /home/ubuntu/charm-test-infra/py3-clients-requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/89/d6/b92297c3a29fe3cf0aa8c65d12f6fb669c69c993b86c69b06b4f03d4afdd/pylxd-2.0.7.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: 
    Installed /tmp/pip-install-dfxhpppw/pylxd/.eggs/requests_unixsocket-0.1.5-py3.6.egg
    Searching for requests!=2.8.0,>=2.5.2
    Reading https://pypi.org/simple/requests/
    Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl#sha256=7bf2a778576d825600030a110f3c0e3e8edc51dfaafe1c146e39a2027784957b
    Best match: requests 2.21.0
    Processing requests-2.21.0-py2.py3-none-any.whl
    Installing requests-2.21.0-py2.py3-none-any.whl to /tmp/pip-install-dfxhpppw/pylxd/.eggs
    writing requirements to /tmp/pip-install-dfxhpppw/pylxd/.eggs/requests-2.21.0-py3.6.egg/EGG-INFO/requires.txt
    
    Installed /tmp/pip-install-dfxhpppw/pylxd/.eggs/requests-2.21.0-py3.6.egg
    Searching for pbr>=1.8
    Reading https://pypi.org/simple/pbr/
    Downloading https://files.pythonhosted.org/packages/14/09/12fe9a14237a6b7e0ba3a8d6fcf254bf4b10ec56a0185f73d651145e9222/pbr-5.1.3-py2.py3-none-any.whl#sha256=8257baf496c8522437e8a6cfe0f15e00aedc6c0e0e7c9d55eeeeab31e0853843
    Best match: pbr 5.1.3
    Processing pbr-5.1.3-py2.py3-none-any.whl
    Installing pbr-5.1.3-py2.py3-none-any.whl to /tmp/pip-install-dfxhpppw/pylxd/.eggs
    
    Installed /tmp/pip-install-dfxhpppw/pylxd/.eggs/pbr-5.1.3-py3.6.egg
    Searching for urllib3>=1.8
    Reading https://pypi.org/simple/urllib3/
    Downloading https://files.pythonhosted.org/packages/c0/1f/516c14fd47ced1a2e2882edd776241c5b707ffc9051cd372843579829994/urllib3-1.25.1-py2.py3-none-any.whl#sha256=a9645efd62b9fc1c7cad8ed93e162aad4c6bfd90e143966ddd4099b78cd244be
    Best match: urllib3 1.25.1
    Processing urllib3-1.25.1-py2.py3-none-any.whl
    Installing urllib3-1.25.1-py2.py3-none-any.whl to /tmp/pip-install-dfxhpppw/pylxd/.eggs
    writing requirements to /tmp/pip-install-dfxhpppw/pylxd/.eggs/urllib3-1.25.1-py3.6.egg/EGG-INFO/requires.txt
    
    Installed /tmp/pip-install-dfxhpppw/pylxd/.eggs/urllib3-1.25.1-py3.6.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dfxhpppw/pylxd/setup.py", line 34, in <module>
        pbr=True)
      File "/home/ubuntu/charm-test-infra/.tox/clients/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/ubuntu/charm-test-infra/.tox/clients/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/ubuntu/charm-test-infra/.tox/clients/lib/python3.6/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,  pkg_resources.ContextualVersionConflict: (urllib3 1.25.1 (/tmp/pip-install-dfxhpppw/pylxd/.eggs/urllib3-1.25.1-py3.6.egg), Requirement.parse('urllib3<1.25,>=1.21.1'), {'requests'})
      File "/home/ubuntu/charm-test-infra/.tox/clients/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.ContextualVersionConflict: (urllib3 1.25.1 (/tmp/pip-install-dfxhpppw/pylxd/.eggs/urllib3-1.25.1-py3.6.egg), Requirement.parse('urllib3<1.25,>=1.21.1'), {'requests'})
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dfxhpppw/pylxd/

ERROR: could not install deps [-r/home/ubuntu/charm-test-infra/py3-clients-requirements.txt]; v = InvocationError('/home/ubuntu/charm-test-infra/.tox/clients/bin/pip install -r/home/ubuntu/charm-test-infra/py3-clients-requirements.txt (see /home/ubuntu/charm-test-infra/.tox/clients/log/clients-1.log)', 1)
___________________________________ summary ____________________________________
ERROR:   clients: could not install deps [-r/home/ubuntu/charm-test-infra/py3-clients-requirements.txt]; v = InvocationError('/home/ubuntu/charm-test-infra/.tox/clients/bin/pip install -r/home/ubuntu/charm-test-infra/py3-clients-requirements.txt (see /home/ubuntu/charm-test-infra/.tox/clients/log/clients-1.log)', 1)`

**Comment by ryan-beisner** [comment]
Please list, verbatim, the commands that were executed to arrive at this.  Thank you.

**Comment by whereisrysmind** [comment]
Steps to Reproduce
```
# from a clean system where ssh-client has not been configured

# clone the project from scratch
git clone https://github.com/openstack-charmers/charm-test-infra.git

cd charm-test-infra
tox
```

**Comment by whereisrysmind** [comment]
Unfortunately, I'm not sure I know enough about it to revert a working system back into a state where it will fail.

**Comment by ryan-beisner** [comment]
Blow away the directory where you have charm-test-infra, re-clone it, and start again.

Here is what works for me, and for our CI automation:

```
ubuntu@beisner-bastion:~/temp$ git clone https://github.com/openstack-charmers/charm-test-infra
Cloning into 'charm-test-infra'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 445 (delta 26), reused 31 (delta 11), pack-reused 399
Receiving objects: 100% (445/445), 82.67 KiB | 617.00 KiB/s, done.
Resolving deltas: 100% (267/267), done.

ubuntu@beisner-bastion:~/temp$ cd charm-test-infra/

ubuntu@beisner-bastion:~/temp/charm-test-infra$ tox
clients create: /home/ubuntu/temp/charm-test-infra/.tox/clients
clients installdeps: -r/home/ubuntu/temp/charm-test-infra/py3-clients-requirements.txt
clients installed: aodhclient==1.2.0,appdirs==1.4.3,argcomplete==1.9.5,asn1crypto==0.24.0,async-generator==1.10,attrs==19.1.0,Babel==2.6.0,bcrypt==3.1.6,certifi==2019.3.9,cffi==1.12.3,chardet==3.0.4,cliff==2.14.1,cmd2==0.9.12,colorama==0.4.1,cryptography==2.6.1,debtcollector==1.21.0,decorator==4.4.0,distro-info==0.0.0,dnspython==1.16.0,dogpile.cache==0.7.1,futures==3.1.1,hvac==0.6.4,idna==2.8,iso8601==0.1.12,Jinja2==2.10.1,jmespath==0.9.4,jsonpatch==1.23,jsonpointer==2.0,jsonschema==2.6.0,juju==0.11.5,juju-deployer==0.11.0,juju-wait==2.7.0,jujubundlelib==0.5.6,jujuclient==0.54.0,jujucrashdump==0.0.0,keystoneauth1==3.14.0,macaroonbakery==1.2.1,MarkupSafe==1.1.1,mojo==0.4.5,monotonic==1.5,msgpack==0.6.1,munch==2.3.2,netaddr==0.7.19,netifaces==0.10.9,openstacksdk==0.27.0,os-client-config==1.32.0,os-service-types==1.6.0,osc-lib==1.12.1,oslo.config==6.8.1,oslo.context==2.22.1,oslo.i18n==3.23.1,oslo.log==3.42.3,oslo.serialization==2.28.2,oslo.utils==3.40.3,paramiko==2.4.2,pbr==5.1.3,pkg-resources==0.0.0,prettytable==0.7.2,protobuf==3.7.1,pyasn1==0.4.5,pycparser==2.19,pyinotify==0.9.6,pylxd==2.0.7,pymacaroons==0.13.0,PyNaCl==1.3.0,pyOpenSSL==19.0.0,pyparsing==2.4.0,pyperclip==1.7.0,pyRFC3339==1.1,python-barbicanclient==4.8.1,python-ceilometerclient==2.9.0,python-cinderclient==4.1.0,python-codetree==0.1.6,python-dateutil==2.8.0,python-designateclient==2.11.0,python-glanceclient==2.16.0,python-heatclient==1.17.0,python-keystoneclient==3.19.0,python-neutronclient==6.12.0,python-novaclient==13.0.0,python-octaviaclient==1.8.0,python-openstackclient==3.18.0,python-swiftclient==3.7.0,pytz==2019.1,PyYAML==5.1,requests==2.21.0,requests-unixsocket==0.1.5,requestsexceptions==1.4.0,rfc3986==1.3.1,simplejson==3.16.0,six==1.12.0,stevedore==1.30.1,tenacity==5.0.4,theblues==0.5.1,urllib3==1.24.2,warlock==1.3.0,wcwidth==0.1.7,websocket-client==0.56.0,websockets==7.0,wrapt==1.11.1,ws4py==0.5.1,zaza==0.0.2.dev1
clients runtests: PYTHONHASHSEED='0'
clients runtests: commands[0] | mojo --version
0.4.5
clients runtests: commands[1] | openstack --version
openstack 3.18.0
____________________________________________________________________________________________ summary ____________________________________________________________________________________________
  clients: commands succeeded
  congratulations :)
ubuntu@beisner-bastion:~/temp/charm-test-infra$ 

ubuntu@beisner-bastion:~/temp/charm-test-infra$ 
ubuntu@beisner-bastion:~/temp/charm-test-infra$ 
ubuntu@beisner-bastion:~/temp/charm-test-infra$ source clientsrc 
(clients) ubuntu@beisner-bastion:~/temp/charm-test-infra$ 
(clients) ubuntu@beisner-bastion:~/temp/charm-test-infra$ openstack --version
openstack 3.18.0
(clients) ubuntu@beisner-bastion:~/temp/charm-test-infra$ 

```

**Comment by ryan-beisner** [comment]
If you are able to reproduce the issue, please provide the exact steps and the console output.  Thank you.

**Comment by ryan-beisner** [comment]
This should have nothing to do with bootstrap, as python virtualenvs are not at all in play.  That is entirely in the realm of Juju and compiled golang code.
